// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: pkg/api/auth/v1/auth.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VerifyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Token         string                 `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyRequest) Reset() {
	*x = VerifyRequest{}
	mi := &file_pkg_api_auth_v1_auth_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyRequest) ProtoMessage() {}

func (x *VerifyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_auth_v1_auth_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyRequest.ProtoReflect.Descriptor instead.
func (*VerifyRequest) Descriptor() ([]byte, []int) {
	return file_pkg_api_auth_v1_auth_proto_rawDescGZIP(), []int{0}
}

func (x *VerifyRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

type VerifyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	Subject       string                 `protobuf:"bytes,2,opt,name=subject,proto3" json:"subject,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyResponse) Reset() {
	*x = VerifyResponse{}
	mi := &file_pkg_api_auth_v1_auth_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyResponse) ProtoMessage() {}

func (x *VerifyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_api_auth_v1_auth_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyResponse.ProtoReflect.Descriptor instead.
func (*VerifyResponse) Descriptor() ([]byte, []int) {
	return file_pkg_api_auth_v1_auth_proto_rawDescGZIP(), []int{1}
}

func (x *VerifyResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *VerifyResponse) GetSubject() string {
	if x != nil {
		return x.Subject
	}
	return ""
}

var File_pkg_api_auth_v1_auth_proto protoreflect.FileDescriptor

const file_pkg_api_auth_v1_auth_proto_rawDesc = "" +
	"\n" +
	"\x1apkg/api/auth/v1/auth.proto\x12\aauth.v1\"%\n" +
	"\rVerifyRequest\x12\x14\n" +
	"\x05token\x18\x01 \x01(\tR\x05token\"@\n" +
	"\x0eVerifyResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x18\n" +
	"\asubject\x18\x02 \x01(\tR\asubject2H\n" +
	"\vAuthService\x129\n" +
	"\x06Verify\x12\x16.auth.v1.VerifyRequest\x1a\x17.auth.v1.VerifyResponseB1Z/github.com/student/tech-ip-sem2/pkg/api/auth/v1b\x06proto3"

var (
	file_pkg_api_auth_v1_auth_proto_rawDescOnce sync.Once
	file_pkg_api_auth_v1_auth_proto_rawDescData []byte
)

func file_pkg_api_auth_v1_auth_proto_rawDescGZIP() []byte {
	file_pkg_api_auth_v1_auth_proto_rawDescOnce.Do(func() {
		file_pkg_api_auth_v1_auth_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_api_auth_v1_auth_proto_rawDesc), len(file_pkg_api_auth_v1_auth_proto_rawDesc)))
	})
	return file_pkg_api_auth_v1_auth_proto_rawDescData
}

var file_pkg_api_auth_v1_auth_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_api_auth_v1_auth_proto_goTypes = []any{
	(*VerifyRequest)(nil),  // 0: auth.v1.VerifyRequest
	(*VerifyResponse)(nil), // 1: auth.v1.VerifyResponse
}
var file_pkg_api_auth_v1_auth_proto_depIdxs = []int32{
	0, // 0: auth.v1.AuthService.Verify:input_type -> auth.v1.VerifyRequest
	1, // 1: auth.v1.AuthService.Verify:output_type -> auth.v1.VerifyResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_api_auth_v1_auth_proto_init() }
func file_pkg_api_auth_v1_auth_proto_init() {
	if File_pkg_api_auth_v1_auth_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_api_auth_v1_auth_proto_rawDesc), len(file_pkg_api_auth_v1_auth_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_api_auth_v1_auth_proto_goTypes,
		DependencyIndexes: file_pkg_api_auth_v1_auth_proto_depIdxs,
		MessageInfos:      file_pkg_api_auth_v1_auth_proto_msgTypes,
	}.Build()
	File_pkg_api_auth_v1_auth_proto = out.File
	file_pkg_api_auth_v1_auth_proto_goTypes = nil
	file_pkg_api_auth_v1_auth_proto_depIdxs = nil
}
